name = "formal-verification/crowfunding"
version = "0.1.0"
compiler = "v1.1.21"
plutus = "v3"
license = "Apache-2.0"

[[dependencies]]
source = "github"
name = "aiken-lang/stdlib"
version = "v2.2.1"

[repository]
user = "formal-verification"
project = "crowfunding"
platform = "github"
